function [fitfun, gof] = createFit(Y, Gap)
%CREATEFIT(Y,GAP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Y
%      Y Output: Gap
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Mar-2013 11:16:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Y, Gap );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf];
opts.Robust = 'LAR';
opts.StartPoint = [3.05629085918503 -0.000594276874885178 9.28154196929093e-05 0.0154585901938339];
opts.Upper = [Inf Inf Inf Inf];

% Fit model to data.
[fitfun, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitfun, xData, yData );
% legend( h, 'Gap vs. Y', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'Y' );
% ylabel( 'Gap' );
% grid on


